import Head from 'next/head'
import PKP from '@/components/pkp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="card bg-base-100 w-full max-w-full shadow-xl border break-all divide-y gap-6">
          <div className="card-body">
            <PKP />
          </div>
        </div>
      </main>
    </>
  )
}
