import Head from 'next/head'
import Sign from '@/components/sign'
import { ReactElement } from 'react'
import DashboardLayout from '@/components/layouts/Dashboard'
import PKP from '@/components/pkp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PKP />
        <Sign />
      </main>
    </>
  )
}


Home.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout title='Home'>{page}</DashboardLayout>
}
