export const evmChains: Record<number, string> = {
    1: 'ethereum',
    137: 'polygon',
    80001: 'mumbai',
    5: 'goerli',
    // 'fantom',
    // 'xdai',
    // 'bsc',
    // 'arbitrum',
    // 'avalanche',
    // 'fuji',
    // 'harmony',
    // 'kovan',
    // 'ropsten',
    // 'rinkeby',
    // 'cronos',
    // 'optimism',
    // 'celo',
    // 'aurora',
    // 'eluvio',
    // 'alfajores',
    // 'xdc',
    // 'evmos',
    // 'evmosTestnet',
    // 'bscTestnet',
    // 'basegoerli',
};
